services:
    - type: web
      name: revam-bnb-api
      runtime: node
      plan: starter
      buildCommand: npm install && npm run build
      startCommand: npm start
      healthCheckPath: /api/health
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 4500
          - key: SUPABASE_URL
            sync: false
          - key: SUPABASE_SERVICE_ROLE_KEY
            sync: false
          - key: TOMORROW_API_KEY
            sync: false
          - key: CORS_ORIGINS
            value: '*'
      autoDeploy: true
      branch: main
